//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPerifelv2.WP.Slider {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Slider {
        
        public static implicit operator global::System.Web.UI.TemplateControl(Slider target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::IntranetPerifelv2.WP.Slider.Slider @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../Style Library/RecursosIntranet/" +
                        "CSS/swiper.css\" />\r\n<html>\r\n<body>\r\n<div id=\"Sliderapp\"  ng-controller=\"SliderCo" +
                        "ntroller\" style=\"width:900px\">\r\n<div class=\"swiper-container main hidden-xs swip" +
                        "er1\">\r\n  <div class=\"arrows\">\r\n    <div class=\"container\">\r\n      <div class=\"co" +
                        "l-md-6\"> <a class=\"arrow-left bundles\" href=\"#\"><span class=\"bpd-icon bpd-icon-b" +
                        "pd-font_99\"></span></a> </div>\r\n      <div class=\"col-md-6\"> <a class=\"arrow-rig" +
                        "ht bundles\" href=\"#\"><span class=\"bpd-icon bpd-icon-bpd-font_98\"></span></a> </d" +
                        "iv>\r\n    </div>\r\n  </div>\r\n  <div class=\"swiper-wrapper\">\r\n    <div class=\"swipe" +
                        "r-slide\" ng-repeat=\" n in SLD\">\r\n      <div class=\"fullbleed-wrapper hidden-xs m" +
                        "ain\" style=\"background-image: url({{n.__metadata.media_src}}); background-positi" +
                        "on-x: 40%;\">\r\n        <div class=\"left-tint\"></div>\r\n        <div class=\"fullble" +
                        "ed-wrapper-inner\">\r\n          <div class=\"container\">\r\n            <div class=\"r" +
                        "ow\">\r\n              <div class=\"col-lg-6 col-md-9 col-sm-9 col-xs-12\">\r\n        " +
                        "        <div class=\"block-copy\">\r\n                  <p class=\"weight10\" style=\"t" +
                        "ext-shadow:1px 1px 1px #000; font-size:40px;\"> \r\n\t\t\t\t\t{{n.Title}}<br>\r\n         " +
                        "         </p>\r\n                  <p  class=\"weight8\" style=\"text-shadow:1px 1px " +
                        "1px #000;font-size:32px\"> \r\n\t\t\t\t\t{{n.Description}}</p>\r\n                  <p cla" +
                        "ss=\"small weight8\" style=\"text-shadow:1px 1px 1px #000;font-size:16px\">\r\n       " +
                        "           {{n.ContentType}}\r\n                  <!--<div class=\"col-md-7 col-md-" +
                        "offset-2\" > <a class=\" btn\" style=\"background-color:#b5191e !important\" href=\"#\"" +
                        " onclick=\"_gaq.push([\'#\']);\"> \r\n  \t\t\t\t\t\t\t\t\tConoce más</a></div>--></div>\r\n      " +
                        "        </div>\r\n            </div>\r\n          </div>\r\n        </div>\r\n      </di" +
                        "v>\r\n    </div>\r\n  </div>\r\n  </div>\r\n  <!-- Add Pagination -->\r\n  <div class=\"swi" +
                        "per-pagination\"></div>\r\n  <!-- Add Arrows -->\r\n  <div class=\"swiper-button-next\"" +
                        "></div>\r\n  <div class=\"swiper-button-prev\"></div>\r\n</div>\r\n<script src=\"../Style" +
                        " Library/RecursosIntranet/Angular/angular.min.js\"></script>\r\n<script src=\"../Sty" +
                        "le Library/RecursosIntranet/JS/swiper.min.js\"></script>\r\n<script src=\"../Style L" +
                        "ibrary/RecursosIntranet/Slider/js/slider.js\"></script>\r\n\r\n</body>\r\n</html>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
