//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaColorada.WebParts.QuickAccessPC {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class QuickAccessPC {
        
        public static implicit operator global::System.Web.UI.TemplateControl(QuickAccessPC target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::PenaColorada.WebParts.QuickAccessPC.QuickAccessPC @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script src=""../../Style%20Library/RecusosPColorada/JS/angular.min.js""></script>
<script src=""../../Style%20Library/RecusosPColorada/JS/quickAccessPC.js""></script>
<link href=""../../Style%20Library/RecusosPColorada/CSS/quickaccessPC.css"" rel=""stylesheet"" />
<link href=""../../Style%20Library/RecusosPColorada/CSS/lightboxPC.css"" rel=""stylesheet"" />

<div id=""quickback"" ng-controller=""getSections"" class=""row"">
    <div class=""quicktext"">
        <div>
            Quiero Acceder a:<br>
            <small>Seleccione el sistema</small>
        </div>
    </div>
    <div ng-repeat=""AccessData in AccessesData"" class=""col-md-3 col-sm-3 col-xs-1  quickicono"">
        <a id=""popup-link"" ng-href=""{{AccessData.Url}}"" ng-click=""evaluateClick(AccessData)""><img ng-src=""{{AccessData.Imagen.Url}}"" alt=""""><p class=""quicksub"">{{AccessData.Title}}</p></a>
    </div>
    <div id=""appsLightbox"" class=""white_content"">
        <ul class=""apps"">
            <li ng-repeat=""app in apps""><a target=""_blank"" ng-href=""{{app.Url.Url}}"">{{app.Title}}</a></li>
        </ul>
    </div>
    <div id=""fadeQA"" ng-click=""hideLightbox()"" class=""black_overlay""></div>
</div>
"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
