//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPerifel.WebParts.VacantesPFL {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class VacantesPFL {
        
        public static implicit operator global::System.Web.UI.TemplateControl(VacantesPFL target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::IntranetPerifel.WebParts.VacantesPFL.VacantesPFL @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script src=""../../Style%20Library/RecusosPColorada/JS/angular.min.js""></script>
<script src=""../../Style%20Library/RecusosPColorada/JS/vacantesPC.js""></script>
<link href=""../../Style%20Library/RecusosPColorada/CSS/bootstrap.css"" rel=""stylesheet"" />
<link href=""../../Style%20Library/RecusosPColorada/CSS/vacantesPC.css"" rel=""stylesheet"" />

<div id=""vacantesPFL"" ng-controller=""getOpenings"" class=""col-sm-11 col-md-11 col-sm-11"">
      <div class=""row"">
         <div class=""col-xs-2 col-sm-2 eventos"">
            <img src=""/_catalogs/masterpage/Perifel/images/vacantes.png"" alt=""""> &nbsp;</div>
         <div class=""col-xs-8 col-sm-7 col-md-8"">
            <span class=""titulosmodulo""> Vacantes disponibles</span> </div>
         <div class=""col-xs-2 col-md-2 col-sm-2"">
            <a ng-href=""{{urlTodos}}""><u class=""rosa""> Ver Todo </u> </a></div>
      </div>
      <div ng-repeat=""opening in _openings"" class=""row"">
         <div class=""col-xs-12 col-sm-12 fondoEv"">
            <h4>{{opening.Title}} </h4>
            <div class=""col-sm-1"">
               <img src=""/_catalogs/masterpage/Perifel/images/people.png"" alt=""""> &nbsp;</div>
            <div class=""ng-binding col-xs-11 col-sm-9"">
               <p>{{opening.Descripcion}}</p>
            </div>
         </div>
      </div>
   </div>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
