//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPerifel.WebParts.BirthdaysPFL {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class BirthdaysPFL {
        
        public static implicit operator global::System.Web.UI.TemplateControl(BirthdaysPFL target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::IntranetPerifel.WebParts.BirthdaysPFL.BirthdaysPFL @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script src=""../../Style%20Library/RecursosIntranetPFL/JS/angular.min.js""></script>
<script src=""../../Style%20Library/RecursosIntranetPFL/JS/swiper.min.js""></script>
<script src=""../../Style%20Library/RecursosIntranetPFL/JS/BirthdaysPFL.js""></script>
<link href=""../../Style%20Library/RecursosIntranetPFL/CSS/birthdaysPFL.css"" rel=""stylesheet"" />

<div id=""Birthdays"" class=""swiper-container swiper-birthdays"">
    <!-- Additional required wrapper -->
    <div ng-controller=""getBirthdays"" class=""swiper-wrapper"">
        <!-- Slides -->
        <div ng-repeat=""person in personsArray"" class=""swiper-slide"">
            <div>
                <div class=""row"">
                    <div class=""col-md-4 col-md-offset-2"">
                        <img alt=""..."" ng-src=""{{person.picture}}"">&nbsp;
                    </div>
                    &nbsp;
                </div>
                <div class=""col-md-12"">{{person.name}}</div>
                <div class=""col-md-12"">{{person.textDate}}</div>
                <div class=""col-md-12"">
                    <p class=""weight2"" lingdex=""23"" style=""font-size: 15px;"">{{person.celebration}}</p>
                </div>
            </div>
        </div>
    </div>
    <!-- If we need navigation buttons -->
    <div class=""swiper-button-prev_bd""></div>
    <div class=""swiper-button-next_bd""></div>
</div>
"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
