//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPerifel.WebParts.NewsPFL {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class NewsPFL {
        
        public static implicit operator global::System.Web.UI.TemplateControl(NewsPFL target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::IntranetPerifel.WebParts.NewsPFL.NewsPFL @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script src=\"../../Style%20Library/RecursosIntranetPFL/JS/angular.min.js\"></s" +
                        "cript>\r\n<script src=\"../../Style%20Library/RecursosIntranetPFL/JS/newsPFL.js\"></" +
                        "script>\r\n<link href=\"../../Style%20Library/RecursosIntranetPFL/CSS/lightboxPFL.c" +
                        "ss\" rel=\"stylesheet\" />\r\n\r\n<div id=\"News\">\r\n    <div ng-controller=\"getNews\" cla" +
                        "ss=\"row\">\r\n        <div ng-repeat=\"news in d\" class=\"col-sm-6 col-md-3\">\r\n      " +
                        "      <div class=\"thumbnail\">\r\n                <img alt=\"...\" src=\'{{news.url}}\'" +
                        ">\r\n                <div class=\"caption\">\r\n                    <h4>{{news.title}}" +
                        "</h4>\r\n                    <p>{{news.description}}</p>\r\n                    <p>\r" +
                        "\n                        <a class=\"btn btn-default\" role=\"button\" ng-click=\"show" +
                        "Lightbox(\'object-\' + news.id)\" href=\"javascript:void(0)\">Más \r\n                 " +
                        "               información</a>\r\n                    </p>\r\n                </div>" +
                        "\r\n                <div ng-attr-id=\"{{\'object-\' + news.id}}\" class=\"white_content" +
                        "\">\r\n                    <div id=\"newsDetails\">\r\n                        <img alt" +
                        "=\"...\" src=\'{{news.url}}\'>\r\n                        <h4>{{news.title}}</h4>\r\n   " +
                        "                     <p>{{news.description}}</p>\r\n                        <p>{{n" +
                        "ews.details}}</p>\r\n                        <a ng-click=\"hideLightbox(\'object-\' +" +
                        " news.id)\" href=\"javascript:void(0)\">Close</a>\r\n                    </div>\r\n    " +
                        "            </div>\r\n            </div>\r\n            <div id=\"fade\" ng-click=\"hid" +
                        "eLightbox(\'object-\' + news.id)\" class=\"black_overlay\"></div>\r\n        </div>\r\n  " +
                        "  </div>\r\n</div>\r\n\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
